// Frontend copy of dealer products — used for UI rendering only.
// The backend has the authoritative list that validates submissions.
export const DEALER_PRODUCTS = [
  "Wheat",
  "Rice / Paddy",
  "Maize / Corn",
  "Jowar / Sorghum",
  "Bajra / Pearl Millet",
  "Ragi / Finger Millet",
  "Barley",
  "Oats",
  "Chickpeas / Gram",
  "Tur / Pigeon Pea",
  "Moong / Green Gram",
  "Urad / Black Gram",
  "Masoor / Lentils",
  "Soybean",
  "Groundnut / Peanut",
  "Potato",
  "Onion",
  "Tomato",
  "Cabbage",
  "Cauliflower",
  "Carrot",
  "Brinjal / Eggplant",
  "Okra / Bhindi",
  "Green Chilli",
  "Cucumber",
  "Pumpkin",
  "Garlic",
  "Ginger",
  "Spinach",
  "Mango",
  "Banana",
  "Apple",
  "Orange",
  "Grapes",
  "Pomegranate",
  "Papaya",
  "Guava",
  "Watermelon",
  "Muskmelon",
  "Coconut",
  "Sugarcane",
  "Cotton",
  "Sunflower",
  "Mustard",
  "Sesame",
  "Turmeric",
  "Cumin",
  "Coriander",
  "Red Chilli",
  "Black Pepper",
  "Tamarind",
  "Flowers",
  "Milk",
  "Eggs",
  "Honey",
  "Fodder",
  "Seeds",
  "Bamboo",
  "Medicinal Plant",
];
