// Frontend copy of labor skills — used for UI rendering only.
// The backend has the authoritative list that validates submissions.
export const LABOR_SKILLS = [
  "Plowing",
  "Harrowing",
  "Land Leveling",
  "Field Cleaning",
  "Seed Sowing",
  "Seedling Transplanting",
  "Planting",
  "Irrigation Management",
  "Watering Crops",
  "Fertilizer Application",
  "Organic Manure Application",
  "Compost Application",
  "Weeding",
  "Thinning",
  "Hoeing",
  "Pest Control",
  "Disease Control",
  "Crop Monitoring",
  "Pruning",
  "Harvesting",
  "Fruit Picking",
  "Vegetable Picking",
  "Crop Cutting",
  "Threshing",
  "Grain Drying",
  "Grain Cleaning",
  "Sorting and Grading",
  "Weighing and Packing",
  "Loading and Unloading",
  "Livestock Feeding",
  "Livestock Herding",
  "Animal Shed Cleaning",
  "Fence Repair",
  "Farm Equipment Maintenance",
  "Tractor Operation",
  "Agricultural Produce Transportation",
];
