/**
 * Authoritative list of allowed dealer products.
 * All product submissions from frontend are validated against this list.
 * Never trust the frontend product list.
 */
const ALLOWED_PRODUCTS = [
  "Wheat",
  "Rice / Paddy",
  "Maize / Corn",
  "Jowar / Sorghum",
  "Bajra / Pearl Millet",
  "Ragi / Finger Millet",
  "Barley",
  "Oats",
  "Chickpeas / Gram",
  "Tur / Pigeon Pea",
  "Moong / Green Gram",
  "Urad / Black Gram",
  "Masoor / Lentils",
  "Soybean",
  "Groundnut / Peanut",
  "Potato",
  "Onion",
  "Tomato",
  "Cabbage",
  "Cauliflower",
  "Carrot",
  "Brinjal / Eggplant",
  "Okra / Bhindi",
  "Green Chilli",
  "Cucumber",
  "Pumpkin",
  "Garlic",
  "Ginger",
  "Spinach",
  "Mango",
  "Banana",
  "Apple",
  "Orange",
  "Grapes",
  "Pomegranate",
  "Papaya",
  "Guava",
  "Watermelon",
  "Muskmelon",
  "Coconut",
  "Sugarcane",
  "Cotton",
  "Sunflower",
  "Mustard",
  "Sesame",
  "Turmeric",
  "Cumin",
  "Coriander",
  "Red Chilli",
  "Black Pepper",
  "Tamarind",
  "Flowers",
  "Milk",
  "Eggs",
  "Honey",
  "Fodder",
  "Seeds",
  "Bamboo",
  "Medicinal Plant",
];

module.exports = { ALLOWED_PRODUCTS };
